export const UPDATE_CITIES_LIST = 'UPDATE_CITIES_LIST'
export const GET_CITY_DETAILS = 'GET_CITY_DETAILS'
export const GET_CITY_DETAILS_SUCCESS = 'GET_CITY_DETAILS_SUCCESS'
export const GET_CITY_DETAILS_FAIL = 'GET_CITY_DETAILS_FAIL'